name: Release - Deploy All

on:
  push:
    branches:
      - 'releases/*'

jobs:

  functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 
        uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - name: Run Eslint
        run: |
          cd functions
          npm install
          npm run lint
      - name: Deploy functions
        run: |
          cd functions
          npm install
          export FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }}
          npm run deploy

  hosting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 
        uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - name: Run Eslint
        run: |
          cd hosting
          npm install
          npm run lint
      - name: Deploy hosting
        run: |
          cd hosting
          npm install
          echo "GATSBY_API_KEY=${{ secrets.GATSBY_API_KEY }}"                           > .env
          echo "GATSBY_AUTH_DOMAIN=${{ secrets.FIREBASE_URL }}"                         >> .env
          echo "GATSBY_DATABASE_URL=${{ secrets.GATSBY_DATABASE_URL }}"                 >> .env
          echo "GATSBY_PROJECT_ID=${{ secrets.GATSBY_PROJECT_ID }}"                     >> .env
          echo "GATSBY_STORAGE_BUCKET=${{ secrets.GATSBY_STORAGE_BUCKET }}"             >> .env
          echo "GATSBY_MESSAGING_SENDER_ID=${{ secrets.GATSBY_MESSAGING_SENDER_ID }}"   >> .env
          echo "GATSBY_VAPID_KEY=${{ secrets.GATSBY_VAPID_KEY }}"                       >> .env
          echo "GATSBY_APPID=${{ secrets.GATSBY_APPID }}"                               >> .env
          npm run build
          export FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }}
          npm run deploy

  database_storage_firestore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 
        uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - name: Deploy Firebase Database, Storage, Firestore config
        run: |
          npm install -g firebase-tools
          firebase deploy --only database,storage,firestore --token ${{ secrets.FIREBASE_TOKEN }}
