name: Node CI

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      - name: Deploy hosting
        run: |
          cd hosting
          npm install && npm install -g firebase-tools
          npm run build
          firebase deploy --project duyet-price-tracker --only hosting --token "$FIREBASE_TOKEN"
