name: Node CI

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 
        uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - name: Deploy functions
        run: |
          cd functions
          npm run lint
          npm install -g firebase-tools
          firebase deploy --token "$FIREBASE_TOKEN" --only functions
      - name: Deploy hosting
        run: |
          cd hosting
          npm install
          npm install -g firebase-tools
          npm run build
          firebase deploy --token "$FIREBASE_TOKEN" --only hosting