name: Node CI

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 
        uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - name: Deploy hosting
        run: |
          cd hosting
          npm install
          npm install -g firebase-tools
          npm run build
          firebase deploy --project duyet-price-tracker --only hosting --token "$FIREBASE_TOKEN"
